import React from 'react';
import { ArrowLeft, Bookmark, Check, Grid3X3, Heart, Lock, Menu, MessageCircle, Pencil, Play, Plus, Repeat2, Settings, Share2, UserCheck, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { auth } from '../lib/firebase';
import { useAppContext } from '../context/AppContext';
import { Post, User } from '../types';
import { cn } from '../lib/utils';
import { ScreenState } from '../components/ui/ScreenState';
import { getApiUrl } from '../lib/api';

type Tab = 'created' | 'private' | 'reposts' | 'saved' | 'liked';
const tabs: Array<{ id: Tab; label: string; icon: React.ElementType; ownerOnly?: boolean }> = [
  { id: 'created', label: 'Moments', icon: Grid3X3 }, { id: 'private', label: 'Private', icon: Lock, ownerOnly: true }, { id: 'reposts', label: 'Reposts', icon: Repeat2 }, { id: 'saved', label: 'Saved', icon: Bookmark, ownerOnly: true }, { id: 'liked', label: 'Liked', icon: Heart, ownerOnly: true },
];

export function Profile() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { currentUser, requireAuth, updateCurrentUser, activeUploads } = useAppContext();
  const isMe = !id || Boolean(currentUser && [currentUser.id, currentUser.uid, currentUser.username].includes(id));
  const targetId = isMe ? currentUser?.id : id;
  const [user, setUser] = React.useState<User | null>(isMe ? currentUser : null);
  const [tab, setTab] = React.useState<Tab>('created');
  const [posts, setPosts] = React.useState<Post[]>([]);
  const [state, setState] = React.useState<'loading' | 'ready' | 'error'>('loading');
  const [following, setFollowing] = React.useState(false);
  const [followedBy, setFollowedBy] = React.useState(false);
  const [menu, setMenu] = React.useState(false);
  const [editing, setEditing] = React.useState(false);
  const [error, setError] = React.useState('');

  React.useEffect(() => {
    if (isMe) { setUser(currentUser); if (!currentUser) requireAuth('Profile', 'Sign in to view your profile.', () => undefined); return; }
    if (!targetId) return;
    const controller = new AbortController(); setState('loading');
    fetch(getApiUrl(`/api/user/${targetId}`), { signal: controller.signal }).then(async response => { if (!response.ok) throw new Error('Profile unavailable'); const data = await response.json(); if (!data?.id && !data?.uid) throw new Error('Profile unavailable'); setUser({ ...data, id: data.id || data.uid }); }).catch(reason => { if (reason?.name !== 'AbortError') setState('error'); });
    return () => controller.abort();
  }, [targetId, isMe, currentUser]);

  React.useEffect(() => {
    if (!user?.id || (tabs.find(item => item.id === tab)?.ownerOnly && !isMe)) return;
    const controller = new AbortController(); setState('loading'); setError('');
    const path = tab === 'created' ? `/api/user/posts/${user.id}` : `/api/user/${tab === 'reposts' ? 'reposts' : tab === 'saved' ? 'saved' : tab === 'liked' ? 'likes' : 'private'}/${user.id}`;
    void (async () => { try { const token = await auth.currentUser?.getIdToken(); const response = await fetch(getApiUrl(path), { signal: controller.signal, headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error(response.status === 403 ? 'This collection is private.' : 'Could not load this collection.'); const data = await response.json(); if (!Array.isArray(data)) throw new Error('Invalid collection response.'); const seen = new Set<string>(); setPosts(data.filter((post: Post) => Boolean(post?.id) && !seen.has(post.id) && Boolean(seen.add(post.id))).sort((a: Post,b: Post) => Number(Boolean(b.isPinned))-Number(Boolean(a.isPinned)))); setState('ready'); } catch (reason: any) { if (reason?.name !== 'AbortError') { setError(reason.message); setState('error'); } } })();
    return () => controller.abort();
  }, [user?.id, tab, isMe]);

  React.useEffect(() => {
    if (isMe || !user?.id || !currentUser) return;
    void auth.currentUser?.getIdToken().then(token => fetch(`/api/follow/${user.id}/status`, { headers: { Authorization: `Bearer ${token}` } })).then(response => response.ok ? response.json() : null).then(data => { if (data) { setFollowing(Boolean(data.isFollowing)); setFollowedBy(Boolean(data.isFollowedBy)); } }).catch(() => undefined);
  }, [isMe, user?.id, currentUser?.id]);

  const follow = () => user && requireAuth('Follow', 'Sign in to follow this creator.', async () => { const previous = following; setFollowing(!previous); setUser(value => value ? { ...value, followersCount: Math.max(0, (value.followersCount || 0) + (previous ? -1 : 1)) } : value); try { const token = await auth.currentUser?.getIdToken(); const response = await fetch(`/api/follow/${user.id}`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(); const data = await response.json(); setFollowing(Boolean(data.followed ?? data.isFollowing)); } catch { setFollowing(previous); setUser(value => value ? { ...value, followersCount: Math.max(0, (value.followersCount || 0) + (previous ? 1 : -1)) } : value); setError('Follow could not be updated.'); } });
  const share = async () => { if (!user) return; const url = `${location.origin}/profile/${user.id}`; try { if (navigator.share) await navigator.share({ title: `${user.displayName} on Omni`, url }); else await navigator.clipboard.writeText(url); } catch {} };
  const totalLikes = tab === 'created' ? posts.reduce((sum, post) => sum + (post.likesCount || 0), 0) : 0;

  if (!user && state === 'loading') return <ScreenState kind="loading" title="Loading profile"/>;
  if (!user) return <ScreenState kind="error" title="Profile unavailable" description="This account could not be loaded." actionLabel="Go back" onAction={() => navigate(-1)}/>;

  return <div className="h-full overflow-y-auto bg-omni-bg pb-24 text-[var(--omni-text-primary)]">
    <header className="sticky top-0 z-30 flex min-h-16 items-center justify-between border-b border-white/[0.06] bg-[rgba(11,11,10,.9)] px-4 backdrop-blur-xl"><button onClick={() => isMe ? setEditing(true) : navigate(-1)} className="grid h-11 w-11 place-items-center rounded-full hover:bg-white/[0.08]" aria-label={isMe ? 'Edit profile' : 'Go back'}>{isMe ? <Pencil size={20}/> : <ArrowLeft size={21}/>}</button><span className="max-w-[55%] truncate text-sm font-semibold">@{user.username}</span><button onClick={() => setMenu(true)} className="grid h-11 w-11 place-items-center rounded-full hover:bg-white/[0.08]" aria-label="Profile menu"><Menu size={21}/></button></header>
    <main>
      <section className="px-5 pb-5 pt-6"><div className="flex items-start gap-5"><button onClick={() => isMe && navigate('/create')} className="relative grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-full border border-white/15 bg-[var(--omni-bg-elevated)] text-2xl font-semibold">{user.avatar ? <img src={user.avatar} alt={user.displayName} className="h-full w-full object-cover"/> : user.displayName.slice(0,1)}{isMe && <span className="absolute bottom-1 right-1 grid h-7 w-7 place-items-center rounded-full border-2 border-[var(--omni-bg-base)] bg-omni-accent text-[#0b0b0a]"><Plus size={15}/></span>}</button><div className="min-w-0 flex-1 pt-1"><h1 className="truncate text-2xl font-bold tracking-tight">{user.displayName}</h1><p className="mt-1 text-sm text-[var(--omni-text-secondary)]">@{user.username}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric value={user.followingCount || 0} label="Following"/><Metric value={user.followersCount || 0} label="Followers"/><Metric value={totalLikes} label="Likes"/></div></div></div>{user.bio && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[var(--omni-text-secondary)]">{user.bio}</p>}
        <div className="mt-5 flex gap-2">{isMe ? <button onClick={() => setEditing(true)} className="min-h-12 flex-1 rounded-xl bg-[var(--omni-text-primary)] text-sm font-semibold text-[var(--omni-bg-base)]">Edit profile</button> : <><button onClick={follow} className={cn('min-h-12 flex-1 rounded-xl text-sm font-semibold', following ? 'border border-white/15 bg-white/[0.05]' : 'bg-omni-accent text-[#0b0b0a]')}>{followedBy && !following ? 'Follow back' : following ? <span className="inline-flex items-center gap-2"><Check size={16}/>Following</span> : 'Follow'}</button><button onClick={() => navigate(`/messages?user=${user.id}`)} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15" aria-label="Message"><MessageCircle size={19}/></button></>}<button onClick={share} className="grid h-12 w-12 place-items-center rounded-xl border border-white/15" aria-label="Share profile"><Share2 size={19}/></button></div>{error && <p role="alert" className="mt-3 text-xs text-[var(--omni-danger)]">{error}</p>}</section>
      <nav className="sticky top-16 z-20 flex border-y border-white/[0.06] bg-[rgba(11,11,10,.94)] backdrop-blur-xl">{tabs.filter(item => isMe || !item.ownerOnly).map(item => <button key={item.id} onClick={() => setTab(item.id)} title={item.label} className={cn('relative grid min-h-14 flex-1 place-items-center text-[var(--omni-text-muted)]', tab === item.id && 'text-[var(--omni-text-primary)]')}><item.icon size={20}/>{tab === item.id && <span className="absolute inset-x-5 bottom-0 h-0.5 bg-omni-accent"/>}</button>)}</nav>
      {state === 'loading' ? <ScreenState kind="loading" title="Loading Moments"/> : state === 'error' ? <ScreenState kind="error" title="Collection unavailable" description={error} actionLabel="Try again" onAction={() => setTab(current => current)}/> : posts.length || (isMe && tab === 'created' && activeUploads.length) ? <div className="grid grid-cols-3 gap-0.5 p-0.5">{isMe && tab === 'created' && activeUploads.map(upload => <div key={upload.id} className="relative aspect-[9/16] overflow-hidden bg-[var(--omni-bg-elevated)]">{upload.previewUrl && <img src={upload.previewUrl} alt="Upload preview" className="h-full w-full object-cover opacity-40"/>}<div className="absolute inset-0 grid place-items-center bg-black/35 text-center text-xs font-semibold"><span>{upload.status === 'error' ? 'Upload failed' : `${upload.progress}%`}</span></div></div>)}{posts.map((post,index) => <button key={post.id} onClick={() => navigate(`/post/${post.id}`, { state: { postsList: posts, initialIndex: index } })} className="relative aspect-[9/16] overflow-hidden bg-[var(--omni-bg-elevated)]">{post.thumbnailUrl || post.type === 'image' ? <img src={post.thumbnailUrl || post.mediaUrl || post.content} alt={post.caption || 'Moment'} loading="lazy" className="h-full w-full object-cover"/> : <video src={`${post.mediaUrl || post.content || `/api/posts/${post.id}/media`}#t=.5`} preload="metadata" muted playsInline className="h-full w-full object-cover"/>}{post.isPinned && <span className="absolute left-1.5 top-1.5 rounded bg-omni-accent px-1.5 py-0.5 text-[9px] font-bold text-[#0b0b0a]">Pinned</span>}<span className="absolute bottom-1.5 left-1.5 flex items-center gap-1 text-[10px] font-semibold text-white drop-shadow"><Play size={10} fill="currentColor"/>{post.viewsCount || 0}</span></button>)}</div> : <ScreenState kind="empty" title={`No ${tabs.find(item => item.id === tab)?.label.toLowerCase()} yet`} description={isMe && tab === 'created' ? 'Your published Moments will appear here.' : 'There is nothing in this collection.'} actionLabel={isMe && tab === 'created' ? 'Create a Moment' : undefined} onAction={isMe && tab === 'created' ? () => navigate('/create') : undefined}/>} 
    </main>
    {menu && <div className="fixed inset-0 z-50 flex items-end bg-black/65" onClick={() => setMenu(false)}><div className="w-full rounded-t-[28px] border-t border-white/10 bg-[var(--omni-bg-surface)] p-4" onClick={event => event.stopPropagation()}><div className="mx-auto mb-4 h-1 w-10 rounded-full bg-white/20"/>{isMe && <button onClick={() => { setMenu(false); navigate('/settings'); }} className="flex min-h-14 w-full items-center gap-3 rounded-xl px-2 text-sm"><Settings size={19} className="text-omni-accent"/>Settings and privacy</button>}<button onClick={() => { setMenu(false); void share(); }} className="flex min-h-14 w-full items-center gap-3 rounded-xl px-2 text-sm"><Share2 size={19}/>Share profile</button><button onClick={() => setMenu(false)} className="mt-2 min-h-12 w-full rounded-xl bg-white/[0.07] text-sm font-semibold">Cancel</button></div></div>}
    {editing && <EditProfile user={user} onClose={() => setEditing(false)} onSave={updated => { setUser(value => value ? { ...value, ...updated } : value); updateCurrentUser(updated); setEditing(false); }}/>} 
  </div>;
}

function Metric({ value, label }: { value: number; label: string }) { return <div><b className="block text-base">{value.toLocaleString()}</b><span className="text-[10px] text-[var(--omni-text-muted)]">{label}</span></div>; }
function EditProfile({ user, onClose, onSave }: { user: User; onClose: () => void; onSave: (value: Partial<User>) => void }) { const [name,setName]=React.useState(user.displayName); const [username,setUsername]=React.useState(user.username); const [bio,setBio]=React.useState(user.bio || ''); const [saving,setSaving]=React.useState(false); const [error,setError]=React.useState(''); const submit=async()=>{setSaving(true);setError('');try{const token=await auth.currentUser?.getIdToken();const response=await fetch('/api/user/profile',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({displayName:name.trim(),username:username.trim(),bio:bio.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Profile could not be saved');onSave(payload);}catch(reason){setError((reason as Error).message);setSaving(false);}}; return <div className="fixed inset-0 z-50 overflow-y-auto bg-omni-bg"><header className="sticky top-0 flex min-h-16 items-center justify-between border-b border-white/[0.06] bg-omni-bg px-4"><button onClick={onClose} className="h-11 px-2 text-sm">Cancel</button><b>Edit profile</b><button onClick={submit} disabled={saving || !name.trim() || !username.trim()} className="h-11 px-2 text-sm font-semibold text-omni-accent disabled:opacity-40">{saving?'Saving…':'Save'}</button></header><main className="mx-auto max-w-md space-y-4 p-4">{error&&<p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<Field label="Display name" value={name} onChange={setName} maxLength={40}/><Field label="Username" value={username} onChange={value=>setUsername(value.toLowerCase().replace(/[^a-z0-9_]/g,''))} maxLength={30}/><label className="block text-xs text-[var(--omni-text-secondary)]">Bio<textarea value={bio} onChange={event=>setBio(event.target.value)} maxLength={180} rows={5} className="mt-2 w-full rounded-xl border border-white/10 bg-[var(--omni-bg-surface)] p-3 text-sm text-white outline-none focus:border-omni-accent"/></label></main></div>; }
function Field({label,value,onChange,maxLength}:{label:string;value:string;onChange:(value:string)=>void;maxLength:number}) { return <label className="block text-xs text-[var(--omni-text-secondary)]">{label}<input value={value} onChange={event=>onChange(event.target.value)} maxLength={maxLength} className="mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-[var(--omni-bg-surface)] px-3 text-sm text-white outline-none focus:border-omni-accent"/></label>; }
